config/routes.rb
TestTask::Application.routes.draw do

  resources :users, except: [:destroy, :show, :edit, :update, :new]

  get '/signup/:invite', to: 'users#new', as: 'signup'
  get '/signup', to: 'users#new'
  match '/users', to: 'users#update', via: [:put, :patch]
  match '/users/edit', to: 'users#edit', via: :get

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :get

  namespace 'admin' do
    resources :invites, only: [:index, :create]
  end

  root :to => 'sessions#new'

end

app/models/invite.rb
class Invite < ActiveRecord::Base

  validates_uniqueness_of :invite

  def initialize
    super
    self.invite = (0...8).map{(65+rand(26)).chr}.join
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  before_save do |user|
    user.email = email.downcase
    if user.phone.blank?
      user.phone = nil
    else
      unless user.phone =~ /\A\+/
        user.phone = '+' + user.phone
      end
    end
  end

  validates_presence_of :name

  validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}, presence: true
  validates :phone, format: {with: /\A\+?\d{11,12}\z/}, allow_blank: true
  validates :password, :password_confirmation, presence: true, length: {minimum: 6}, :unless => lambda{ |user| user.password.blank? }, on: :update
  validates :password, :password_confirmation, presence: true, length: {minimum: 6}, on: :create

  after_validation {self.errors.messages.delete(:password_digest)}
end

app/controllers/admin/invites_controller.rb
class Admin::InvitesController < ApplicationController
  def index
    @invites = last_10_invites
  end

  def create
    if permitted_params[:email] =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      new_invite = Invite.new
      new_invite.save
      InviteMailer.invitation_email(permitted_params[:email], new_invite.invite).deliver
    else
      @errors = ['Invalid email']
    end
    @invites = last_10_invites
    render 'index'
  end

  private
    def last_10_invites
      Invite.order('created_at desc').limit 10
    end

    def permitted_params
      params.require(:sender).permit(:email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  def handle_univeified_request
    sign_out
    super
  end

  protected
    def signed_out_user
      redirect_to '/users' if signed_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :signed_out_user, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user
      redirect_to '/users'
    else
      @errors = ['Invalid email/password combination']
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, except: [:new, :create]
  before_filter :signed_out_user, only: [:new, :create]
  before_filter :check_invitation, only: [:new]

  def index
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params)
    if @user.save
      sign_in @user
      redirect_to '/users'
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    permitted_params.delete(:password) if permitted_params[:password].blank?
    permitted_params.delete(:password_confirmation) if permitted_params[:password_confirmation].blank?
    if @user.update_attributes(permitted_params)
      redirect_to '/users'
    else
      render 'edit'
    end
  end

  private
    def signed_in_user
      redirect_to signin_path unless signed_in?
    end

    def check_invitation
      if (_invite = Invite.find_by_invite(params[:invite])) && _invite.status
        _invite.status = false
        _invite.save
      else
        redirect_to root_path
      end
    end

    def permitted_params
      params.require(:user).permit(:email, :name, :phone, :password, :password_confirmation)
    end
end

app/helpers/admin/invites_helper.rb
module Admin::InvitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in user
    cookies.permanent[:user_id] = user.id
  end

  #def curent_user=(user)
  #  @curent_user = user
  #end

  def current_user
    @current_user ||= User.find_by_id(cookies[:user_id])
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_id)
  end
end

app/views/admin/invites/index.html.erb
<% content_for :in_out_ui do %>
    Send invite to:
    <%= render 'shared/error_messages' %>

    <%= form_for :sender, url: admin_invites_path do |f| %>
        <%= f.text_field :email, placeholder: :Email, class: 'e-input' %>
        <%= f.submit :Send, class: 'e-button' %>
    <% end %>
<% end %>

<table class='b-table'>
  <% @invites.each do |invite| %>
    <tr><td><%= invite.invite %></td><td><%= invite.status ? 'opened' : 'closed' %></td></tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <div class="wrapper-background">
    <%= image_tag 'saha.jpg', class: 'wrapper-background-img' %>
  </div>
  <div class="wrapper-content">
    <div class="wrapper-content-header">
      <% :in_out_ui %>
      <%= content_for?(:in_out_ui) ? yield(:in_out_ui) : (link_to 'Log out', signout_path, class: 'e-link') %>
    </div>
    <div class="wrapper-content-body">
      <% :content %>
      <%= yield %>
      <% if Rails.env.development? %>
          <div class='b-debug'>
            <%= debug(params) %>
          </div>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @errors %>
    <div class="b-errors">
      <ul>
        <% @errors.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_user_errors_messages.html.erb
<div class="b-errors">
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/users/edit.html.erb
Edit profile:
<%= render 'shared/user_errors_messages' %>

<%= form_for @user, url: '/users' do |f| %>
    <%= f.text_field :email, placeholder: :Email, class: 'e-input' %>
    <%= f.text_field :name, placeholder: :Name, class: 'e-input' %>
    <%= f.text_field :phone, placeholder: :Phone, class: 'e-input' %>
    <%= f.password_field :password, placeholder: :Password, class: 'e-input' %>
    <%= f.password_field :password_confirmation, placeholder: 'Repeat password', class: 'e-input' %>
    <%= f.submit :Update, class: 'e-button' %>
<% end %>

app/views/users/index.html.erb
<%= @user.name %><br/>
        Email: <%= @user.email %><br/>
        Phone: <% if @user.phone%><%= @user.phone %><br/>
<% else %>please <%= link_to 'add phone', '/users/edit', class: 'e-link' %><br/>
<% end %>
        <%= link_to 'Edit profile', '/users/edit', class: 'e-link' %>

app/views/users/new.html.erb
<% content_for :in_out_ui do %>
<%= link_to 'Login form', signin_path, class: 'e-link' %>
<% end %>
Register:
<%= render 'shared/user_errors_messages' %>

<%= form_for(@user) do |f| %>
    <%= f.text_field :email, class: 'e-input', placeholder: 'Email' %>
    <%= f.text_field :name, class: 'e-input', placeholder: 'Name' %>
    <%= f.password_field :password, class: 'e-input', placeholder: 'Password' %>
    <%= f.password_field :password_confirmation, class: 'e-input', placeholder: 'Repeat password' %>
    <%= f.submit 'Register', class: 'e-button' %>
<% end %>